ylabel('$V$','fontsize',14,'interpreter','latex')
xlabel('$Tiempo(seg)$','fontsize',14,'interpreter','latex')
legend('$V_{carga}$','$Ref$','fontsize',14,'interpreter','latex')
title('Voltaje en la carga','fontsize',14,'interpreter','latex')
%xlim([0 0.26])

ylabel('$V$','fontsize',14,'interpreter','latex')
xlabel('$Tiempo(seg)$','fontsize',14,'interpreter','latex')
%legend('$V_{carga}$','$Ref$','fontsize',14,'interpreter','latex')
title('Acción de control en el VSI','fontsize',14,'interpreter','latex')